---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: deploy
    image: dijitle/kubectl:0.0.2
    environment:
      KUBERNETES_CERT:
        from_secret: k8s_cert
      KUBERNETES_TOKEN:
        from_secret: k8s_token
    commands:
      - kubectl-init.sh
      - kubectl get nodes

---
kind: signature
hmac: 09029131067f770899755f1d569074b280ab6c74cf3fb6f727495c3ba1eb736b

...
