---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl get nodes

---
kind: signature
hmac: 4ae54ec4e1ab02b2ac27bff3e44ac4f02cee16eb7722dd873ada9a49f6af86be

...
