apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  labels:
    k8s-app: dijitle-metra
  name: dijitle-metra
  namespace: metra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dijitle-metra
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: dijitle-metra
    spec:
      containers:
      - image: metra:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: secretKey
          valueFrom:
            secretKeyRef:
              name: gtfsSecret
              key: secretKey 
        - name: accessKey
          valueFrom:
            secretKeyRef:
              name: gtfsSecret
              key: accessKey     
        name: dijitle-metra
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler      
      terminationGracePeriodSeconds: 30     